name: ALAMPAT CI
on: [push, pull_request]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node modules and dependencies
        run: npm i --global npm@6, npm i nyc

      - name: Run tests
        run: npm run test #-- --no-watch --no-progress #--browsers=ChromeHeadlessCI
